// File generated by FlutterFire CLI.
// This file should be regenerated using: flutterfire configure
// Run the command in the project root to generate platform-specific Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrsD0gjP6UIxJxFu5vfHV2uDAWJUiV3E',
    appId: '1:15364239615:android:fe80327edf9003814d5cca',
    messagingSenderId: '15364239615',
    projectId: 'just-launder-48cc0',
    storageBucket: 'just-launder-48cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAT96RcCBI6WAKPVmvkdzt1cSe_8AF2sc',
    appId: '1:15364239615:ios:967f0f1776a49f4c4d5cca',
    messagingSenderId: '15364239615',
    projectId: 'just-launder-48cc0',
    storageBucket: 'just-launder-48cc0.firebasestorage.app',
    iosBundleId: 'just.launder.tenant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.justlaunder.customer',
  );
}

// Firebase configuration instructions:
// 1. Run: flutterfire configure
// 2. Select Firebase project
// 3. This will generate the actual configuration for all platforms
